/*Department*/
INSERT INTO DEPARTMENT (ID, DEP_NAME) VALUES (1, '開發1科');
INSERT INTO DEPARTMENT (ID, DEP_NAME) VALUES (2, '開發2科');
INSERT INTO DEPARTMENT (ID, DEP_NAME) VALUES (3, '開發3科');
INSERT INTO DEPARTMENT (ID, DEP_NAME) VALUES (4, '開發4科');
INSERT INTO DEPARTMENT (ID, DEP_NAME) VALUES (5, '開發5科');

/*Employee*/
INSERT INTO EMPLOYEE (ID, ADDRESS, AGE, DEP_ID,GENDER,NAME,PHONE) 
  VALUES (1, 'test1',30,1,'Male','Ted','0911123456');
INSERT INTO EMPLOYEE (ID, ADDRESS, AGE, DEP_ID,GENDER,NAME,PHONE) 
  VALUES (2, 'test2',31,2,'Female','Lin','0911123451');
INSERT INTO EMPLOYEE (ID, ADDRESS, AGE, DEP_ID,GENDER,NAME,PHONE) 
  VALUES (3, 'test3',32,3,'Male','Fred','0912123456');
INSERT INTO EMPLOYEE (ID, ADDRESS, AGE, DEP_ID,GENDER,NAME,PHONE) 
  VALUES (4, 'test4',33,4,'Male','Kenny','0911123453');
INSERT INTO EMPLOYEE (ID, ADDRESS, AGE, DEP_ID,GENDER,NAME,PHONE) 
  VALUES (5, 'test5',34,5,'Female','Rock','0911123457');
