INSERT INTO DEPARTMENT (ID, DEP_NAME) VALUES (1, '開發1科');
INSERT INTO DEPARTMENT (ID, DEP_NAME) VALUES (2, '開發2科');
INSERT INTO DEPARTMENT (ID, DEP_NAME) VALUES (3, '開發3科');
INSERT INTO DEPARTMENT (ID, DEP_NAME) VALUES (4, '開發4科');
INSERT INTO DEPARTMENT (ID, DEP_NAME) VALUES (5, '開發5科');

/*INSERT INTO EMPLOYEE (ID, NAME, DEP_ID, GENDER, PHONE, ADDRESS, AGE, ) VALUES (1, '開發1科');*/
